# Generated by Django 3.2.23 on 2024-03-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background',
            field=models.CharField(default='default_bg.jpg', max_length=100),
        ),
    ]
