# Generated by Django 3.2.23 on 2024-03-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_userprofile_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
    ]
